name: Automerge

on:
  schedule:
    - cron: 0 12 * * *
  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: "merge"
